In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import tqdm
import matplotlib.pyplot as plt

In [2]:
from sklearn.metrics import mean_squared_error

In [4]:
raw_dataset = pd.read_csv('California_housing.csv')

In [9]:
raw_dataset.fillna('UNK',inplace=True)

## Gradient Descent
$$ MSE = \frac{1}{n}\sum_{i=1}^{n} (y_i - \hat{y_i})^2 \quad \textrm{where} \quad \hat{y_i} = mx_i + b $$
$$𝑓(𝑚,𝑏)= \frac{1}{n}\sum_{i=1}^{n}(y_i - (mx_i+b))^2$$

**Partial Derivative With Respect to m**
$$\frac{\partial f}{\partial m} = \frac{1}{n}\sum_{i=1}^{n}-2x_i(y_i - (mx_i+b))$$

**Partial Derivative With Respect to b**

$$\frac{\partial f}{\partial b} = \frac{1}{n}\sum_{i=1}^{n}-2(y_i - (mx_i+b))$$

In [ ]:
def predict(x,weight,intercept):
    
    y = mx + c
    y = weight @ x + intercept

def mse_loss(y,y_pred):
    n=len(y)
    return (1/n)*((y - y_pred)**2)
    

def dldw(x,y,y_pred):
    n = len(y) 
    dldw = (1/n)*sum(2*(-x)*(y.reshape(n,1)-y_pred.reshape(n,1)))
    return dldw


def dldb(y,y_pred):
    n = len(y)
    return (-2/n) * np.sum(y - y_pred)

def gradient_descent(x,y):
    pass

In [136]:
def dldb(y,y_predicted):
    n=len(y)
    s=0
    for i in range(len(y)):
        s+=-(y[i]-y_predicted[i])
    return (2/n) * s

In [113]:
x = np.array([[1,2],[2,4],[3,5],[4,2]])
y = np.array([2,5,2,2])
y_pred = np.array([4,8,3,4])


In [165]:
weight = np.random.randn(4,2)

In [170]:
weight

array([[-2.02735231,  0.50367845],
       [ 1.48579928, -0.9119291 ],
       [ 0.25308029, -0.8668772 ],
       [ 1.32040384, -0.87866808]])

In [169]:
x

array([[1, 2],
       [2, 4],
       [3, 5],
       [4, 2]])

In [168]:
weight* x

array([[-2.02735231,  1.0073569 ],
       [ 2.97159856, -3.64771641],
       [ 0.75924087, -4.33438602],
       [ 5.28161534, -1.75733616]])

In [167]:
weight @ x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

In [158]:
from sklearn.model_selection import train_test_split

#Splitting Feature and Target into Training and Test Data.
train_feature_df, test_feature_df = train_test_split(features,shuffle = True, test_size = 0.25, random_state=12)
train_target_df, test_target_df = train_test_split(target,shuffle = True, test_size = 0.25, random_state=12)

In [32]:
features = raw_dataset[['Latitude', 'Longitude', 'HouseAge', 'AveRooms','AveBedrms', 'Population', 'AveOccup', 'MedInc']]
target = raw_dataset[['Housing_Value']]

In [33]:
from sklearn.model_selection import train_test_split

#Splitting Feature and Target into Training and Test Data.
train_feature_df, test_feature_df = train_test_split(features,shuffle = True, test_size = 0.25, random_state=12)
train_target_df, test_target_df = train_test_split(target,shuffle = True, test_size = 0.25, random_state=12)

In [35]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

#Normalizing the data using Standard Scaler and fiiting it into the dataset.
scaler = StandardScaler()
X_train_scaled=pd.DataFrame(scaler.fit_transform(train_feature_df),columns=train_feature_df.columns, index=train_feature_df.index)